"""Seed du lieu mau K12."""
from __future__ import annotations
from .models import BaiHoc, CauHoi


def seed_bai_hoc() -> list[BaiHoc]:
    return [
        BaiHoc(id="lop1-toan-cong", mon="toan", lop=1, tieu_de="Lam quen phep cong pham vi 10",
               muc_tieu="Biet gop 2 nhom do vat va viet phep cong.",
               noi_dung="3 qua tao + 2 qua tao = 5 qua tao. Phep cong la gop lai.",
               thoi_luong_phut=10, do_kho=1, thu_tu=1),
        BaiHoc(id="lop2-tv-tapdoc", mon="tieng_viet", lop=2, tieu_de="Tap doc: Chu ong cham chi",
               muc_tieu="Doc troi chay, hieu y cham chi.",
               noi_dung="Sang som, chu ong bay di hut mat.",
               thoi_luong_phut=10, do_kho=1, thu_tu=1),
        BaiHoc(id="lop3-toan-nhan", mon="toan", lop=3, tieu_de="Bang nhan 3 that vui",
               muc_tieu="Thuoc bang nhan 3.",
               noi_dung="3x1=3, 3x2=6, 3x3=9... Moi lan them 3.",
               thoi_luong_phut=12, do_kho=1, thu_tu=1),
        BaiHoc(id="lop4-kh-nuoc", mon="khoa_hoc", lop=4, tieu_de="Vong tuan hoan cua nuoc",
               muc_tieu="Ke duoc bay hoi - ngung tu - mua.",
               noi_dung="Nuoc bay hoi thanh may, may roi thanh mua.",
               thoi_luong_phut=12, do_kho=1, thu_tu=1),
        BaiHoc(id="lop5-tv-mieuta", mon="ngu_van", lop=5, tieu_de="Mieu ta con vat em yeu",
               muc_tieu="Viet doan van 5-7 cau.",
               noi_dung="Mo bai - than bai - ket bai.",
               thoi_luong_phut=15, do_kho=2, thu_tu=1),
        BaiHoc(id="lop6-toan-phanso", mon="toan", lop=6, tieu_de="Phan so bang nhau",
               muc_tieu="Nhan biet va rut gon phan so.",
               noi_dung="1/2 = 2/4 = 3/6.",
               thoi_luong_phut=15, do_kho=2, thu_tu=1),
        BaiHoc(id="lop6-anh-hts", mon="tieng_anh", lop=6, tieu_de="Present Simple that de",
               muc_tieu="Chia dong tu ngoi 3 so it.", noi_dung="I play - She plays.",
               thoi_luong_phut=12, do_kho=1, thu_tu=1),
        BaiHoc(id="lop7-van-cadao", mon="ngu_van", lop=7, tieu_de="Ca dao ve tinh cam gia dinh",
               muc_tieu="Cam nhan ve dep tinh than.", noi_dung="Cong cha nhu nui Thai Son...",
               thoi_luong_phut=15, do_kho=2, thu_tu=1),
        BaiHoc(id="lop8-hoa-oxi", mon="hoa_hoc", lop=8, tieu_de="Oxi va su chay",
               muc_tieu="Biet tinh chat cua oxi.", noi_dung="Oxi duy tri su chay. C+O2->CO2.",
               thoi_luong_phut=15, do_kho=2, thu_tu=1),
        BaiHoc(id="lop9-toan-ptbac2", mon="toan", lop=9, tieu_de="Phuong trinh bac hai mot an",
               muc_tieu="Tinh delta va tim nghiem.", noi_dung="ax^2+bx+c=0. Delta=b^2-4ac.",
               thoi_luong_phut=20, do_kho=3, thu_tu=1),
        BaiHoc(id="lop10-ly-cd", mon="vat_ly", lop=10, tieu_de="Chuyen dong thang bien doi deu",
               muc_tieu="Dung v=v0+a*t.", noi_dung="Xe tang toc deu.",
               thoi_luong_phut=18, do_kho=2, thu_tu=1),
        BaiHoc(id="lop11-hoa-este", mon="hoa_hoc", lop=11, tieu_de="Este va chat beo",
               muc_tieu="Nho cong thuc tong quat.", noi_dung="RCOOR'. Chat beo la trieste.",
               thoi_luong_phut=18, do_kho=3, thu_tu=1),
        BaiHoc(id="lop12-toan-hamso", mon="toan", lop=12, tieu_de="Khao sat ham so bac ba",
               muc_tieu="Lap BBT va ve do thi.", noi_dung="B1 TXD. B2 y'. B3 nghiem. B4 BBT.",
               thoi_luong_phut=25, do_kho=3, thu_tu=1),
        BaiHoc(id="lop12-anh-mdqh", mon="tieng_anh", lop=12, tieu_de="Menh de quan he",
               muc_tieu="Dung who/which/that.", noi_dung="The book which I bought is interesting.",
               thoi_luong_phut=20, do_kho=2, thu_tu=1),
    ]


def seed_cau_hoi() -> list[CauHoi]:
    return [
        CauHoi(id="q1", bai_hoc_id="lop1-toan-cong", mon="toan", lop=1,
               cau_hoi="3 + 2 = ?", lua_chon=["4", "5", "6"],
               dap_an_dung="5", giai_thich="Gop 3 va 2 duoc 5.", diem=1),
        CauHoi(id="q2", bai_hoc_id="lop3-toan-nhan", mon="toan", lop=3,
               cau_hoi="3 x 4 = ?", lua_chon=["7", "12", "9"],
               dap_an_dung="12", giai_thich="3+3+3+3=12.", diem=1),
        CauHoi(id="q3", bai_hoc_id="lop6-toan-phanso", mon="toan", lop=6,
               cau_hoi="Phan so nao bang 1/2?", lua_chon=["2/4", "1/3", "3/4"],
               dap_an_dung="2/4", giai_thich="Nhan ca tu va mau voi 2.", diem=1),
        CauHoi(id="q4", bai_hoc_id="lop9-toan-ptbac2", mon="toan", lop=9,
               cau_hoi="Nghiem cua x^2-4=0?", lua_chon=["x=2", "x=2; x=-2", "x=-2"],
               dap_an_dung="x=2; x=-2", giai_thich="x^2=4 nen x=+-2.", diem=2),
        CauHoi(id="q5", bai_hoc_id="lop6-anh-hts", mon="tieng_anh", lop=6,
               cau_hoi="She ___ to school.", lua_chon=["go", "goes", "going"],
               dap_an_dung="goes", giai_thich="Ngoi 3 so it them s.", diem=1),
        CauHoi(id="q6", bai_hoc_id="lop10-ly-cd", mon="vat_ly", lop=10,
               cau_hoi="v0=2,a=3,t=4. Tinh v?", lua_chon=["14 m/s", "12 m/s", "10 m/s"],
               dap_an_dung="14 m/s", giai_thich="v=2+3*4=14.", diem=2),
        CauHoi(id="q7", bai_hoc_id="lop8-hoa-oxi", mon="hoa_hoc", lop=8,
               cau_hoi="Khi nao duy tri su chay?", lua_chon=["Oxi", "Nito", "CO2"],
               dap_an_dung="Oxi", giai_thich="Oxi duy tri su chay.", diem=1),
        CauHoi(id="q8", bai_hoc_id="lop12-toan-hamso", mon="toan", lop=12,
               cau_hoi="Buoc dau KS ham so?", lua_chon=["Tim TXD", "Ve do thi", "Tinh y''"],
               dap_an_dung="Tim TXD", giai_thich="Tim TXD truoc.", diem=1),
    ]
